# Generated by Django 2.2 on 2021-03-05 15:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_topic_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronlog',
            name='ended_at',
            field=models.DateTimeField(auto_now=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
